import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1779418327103 implements MigrationInterface {
    name = 'Migrations1779418327103'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`audit_logs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user\` int NULL, \`action\` varchar(255) NOT NULL, \`module\` varchar(255) NOT NULL, \`old_data\` json NULL, \`new_data\` json NULL, \`ip\` varchar(255) NULL, \`user_agent\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`employees\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`name\` varchar(255) NOT NULL, \`phone\` varchar(255) NULL, \`position\` varchar(255) NULL, \`salary\` decimal(10,2) NOT NULL, \`overtime_rate\` decimal(5,2) NOT NULL DEFAULT '0.00', \`absent_deduction\` decimal(10,2) NOT NULL DEFAULT '0.00', \`bonus\` decimal(10,2) NOT NULL DEFAULT '0.00', \`advance_salary\` decimal(10,2) NOT NULL DEFAULT '0.00', \`payable_salary\` decimal(10,2) NOT NULL DEFAULT '0.00', \`attendance_days\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`expenses\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`category\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`quantity\` int NOT NULL DEFAULT '1', \`unit_price\` decimal(10,2) NOT NULL, \`total_amount\` decimal(12,2) NOT NULL, \`payment_type\` varchar(255) NOT NULL DEFAULT 'cash', \`receipt_image\` varchar(255) NULL, \`expense_date\` date NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`income_changes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`type\` varchar(255) NOT NULL, \`category\` varchar(255) NULL, \`amount\` decimal(12,2) NOT NULL, \`description\` text NULL, \`change_date\` date NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`installation_rules\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`name\` varchar(255) NOT NULL, \`fee\` decimal(10,2) NOT NULL, \`description\` text NULL, \`status\` varchar(255) NOT NULL DEFAULT 'active', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NULL, \`type\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`message\` text NOT NULL, \`read\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`regions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`village_name\` varchar(255) NOT NULL, \`myanmar_name\` varchar(255) NULL, \`township\` varchar(255) NULL, \`latitude\` decimal(10,7) NULL, \`longitude\` decimal(10,7) NULL, \`coverage_radius\` decimal(10,2) NULL, \`active_users\` int NOT NULL DEFAULT '0', \`revenue\` decimal(12,2) NULL, \`coverage_percent\` decimal(5,2) NOT NULL DEFAULT '0.00', \`status\` varchar(255) NOT NULL DEFAULT 'active', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`subscriptions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`user_id\` int NOT NULL, \`package_id\` int NOT NULL, \`payment_type\` varchar(255) NOT NULL, \`months\` int NOT NULL DEFAULT '1', \`discount_percent\` decimal(5,2) NOT NULL DEFAULT '0.00', \`extra_months\` int NOT NULL DEFAULT '0', \`installation_fee\` decimal(10,2) NOT NULL DEFAULT '0.00', \`cable_fee\` decimal(10,2) NOT NULL DEFAULT '0.00', \`total_amount\` decimal(10,2) NOT NULL, \`start_date\` date NOT NULL, \`end_date\` date NOT NULL, \`payment_status\` varchar(255) NOT NULL DEFAULT 'paid', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`customer_id\` varchar(255) NULL, \`username\` varchar(255) NOT NULL, \`phone\` varchar(255) NULL, \`email\` varchar(255) NULL, \`password\` varchar(255) NOT NULL, \`address\` varchar(255) NULL, \`village\` varchar(255) NULL, \`township\` varchar(255) NULL, \`latitude\` decimal(10,7) NULL, \`longitude\` decimal(10,7) NULL, \`region_id\` int NULL, \`package_id\` int NULL, \`onu_mac\` varchar(255) NULL, \`onu_serial\` varchar(255) NULL, \`onu_type\` varchar(255) NULL, \`port_number\` varchar(255) NULL, \`cable_distance\` decimal(10,2) NULL, \`installation_type\` varchar(255) NULL, \`installation_fee\` decimal(10,2) NULL, \`subscription_start_date\` date NULL, \`subscription_end_date\` date NULL, \`remaining_days\` int NOT NULL DEFAULT '0', \`status\` enum ('active', 'suspended', 'expired') NOT NULL DEFAULT 'active', \`last_payment_date\` date NULL, \`last_online_at\` timestamp NULL, \`balance\` decimal(10,2) NOT NULL DEFAULT '0.00', \`notes\` text NULL, \`role\` varchar(255) NOT NULL DEFAULT 'admin', UNIQUE INDEX \`IDX_c7bc1ffb56c570f42053fa7503\` (\`customer_id\`), UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`packages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`name\` varchar(255) NOT NULL, \`speed\` varchar(255) NULL, \`category\` varchar(255) NULL, \`base_price\` decimal(10,2) NOT NULL, \`installation_fee\` decimal(10,2) NOT NULL DEFAULT '0.00', \`status\` varchar(255) NOT NULL DEFAULT 'active', \`description\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`settings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`key\` varchar(255) NOT NULL, \`value\` text NOT NULL, \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_c8639b7626fa94ba8265628f21\` (\`key\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`subscription_rules\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`name\` varchar(255) NOT NULL, \`min_months\` int NOT NULL DEFAULT '1', \`discount_percent\` decimal(5,2) NOT NULL DEFAULT '0.00', \`extra_months\` int NOT NULL DEFAULT '0', \`description\` text NULL, \`status\` varchar(255) NOT NULL DEFAULT 'active', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` ADD CONSTRAINT \`FK_d0a95ef8a28188364c546eb65c1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` ADD CONSTRAINT \`FK_ed655e6276526f4f1b8167ff6be\` FOREIGN KEY (\`package_id\`) REFERENCES \`packages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_1901e9aae03c8897b7dd460c27f\` FOREIGN KEY (\`region_id\`) REFERENCES \`regions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_2374ba6e2aa8e721abd7fcd3f1f\` FOREIGN KEY (\`package_id\`) REFERENCES \`packages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_2374ba6e2aa8e721abd7fcd3f1f\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_1901e9aae03c8897b7dd460c27f\``);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` DROP FOREIGN KEY \`FK_ed655e6276526f4f1b8167ff6be\``);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` DROP FOREIGN KEY \`FK_d0a95ef8a28188364c546eb65c1\``);
        await queryRunner.query(`DROP TABLE \`subscription_rules\``);
        await queryRunner.query(`DROP INDEX \`IDX_c8639b7626fa94ba8265628f21\` ON \`settings\``);
        await queryRunner.query(`DROP TABLE \`settings\``);
        await queryRunner.query(`DROP TABLE \`packages\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_c7bc1ffb56c570f42053fa7503\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`subscriptions\``);
        await queryRunner.query(`DROP TABLE \`regions\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`installation_rules\``);
        await queryRunner.query(`DROP TABLE \`income_changes\``);
        await queryRunner.query(`DROP TABLE \`expenses\``);
        await queryRunner.query(`DROP TABLE \`employees\``);
        await queryRunner.query(`DROP TABLE \`audit_logs\``);
    }

}
